source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/su.softcom.cldt.testing.gtest.core.GTestLibraryRegistrator.xml,\
               plugin.xml,\
               OSGI-INF/su.softcom.cldt.testing.gtest.internal.core.TestIndexService.xml,\
               OSGI-INF/su.softcom.cldt.testing.gtest.internal.core.BuildFinishedListener.xml,\
               OSGI-INF/,\
               resources/
